name: "cifar10"                       # Name of the dataset being used
data_dir: ${paths.data_dir}           # Directory path for the dataset, dynamically set from paths
batch_size: 128                       # Number of samples per batch for training
num_workers: ${compute.num_workers}   # Number of worker threads for data loading
pin_memory: ${compute.pin_memory}     # Whether to use pinned memory for data transfer to GPU